package Main;
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

public class Login extends javax.swing.JFrame {
    private Connection conn = new Koneksi().connect();
    private boolean isPasswordPlaceholder = true;
    
    public Login() {
        initComponents();
        kosong();
        setupPasswordField();
    }
    
    void kosong() {
        txtusername.setText("Username");
        txtpassword.setText("Password");
        txtpassword.setEchoChar((char) 0);
        isPasswordPlaceholder = true;
        
        txtusername.setForeground(Color.GRAY);
        txtpassword.setForeground(Color.GRAY);
    }
    
    private void setupPasswordField() {
        txtpassword.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (isPasswordPlaceholder) {
                    txtpassword.setText("");
                    txtpassword.setEchoChar('*');
                    txtpassword.setForeground(Color.BLACK);
                    isPasswordPlaceholder = false;
                }
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                if (txtpassword.getPassword().length == 0) {
                    txtpassword.setText("Password");
                    txtpassword.setEchoChar((char) 0);
                    txtpassword.setForeground(Color.GRAY);
                    isPasswordPlaceholder = true;
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        key = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        key.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jPanel1.add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 30, 40));

        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        judul.setFont(new java.awt.Font("Teko SemiBold", 1, 24)); // NOI18N
        judul.setText("Gudang Aquatic");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 30));

        txtusername.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 40));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\aldiy\\OneDrive\\Documents\\NetBeansProjects\\Apps_Gudang\\src\\images\\aquatic.png")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 290, 380));

        login.setBackground(new java.awt.Color(0, 0, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 40));

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Male.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 50));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(614, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
    dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
    String username = txtusername.getText();
        String password;
        
        // PERBAIKAN: Cara mengambil password yang benar
        if (isPasswordPlaceholder) {
            password = ""; // Jika masih placeholder, password kosong
        } else {
            password = new String(txtpassword.getPassword()); // Ambil password asli
        }
        
        // Debug input
        System.out.println("Login attempt - Username: " + username + ", Password: " + password);
        
        if (username.equalsIgnoreCase("") || username.equals("Username")) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!");
            return;
        } 
        
        if (password.equals("") || password.equals("Password") || isPasswordPlaceholder) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!");
            return;
        }
        
        try {
            String query = "SELECT id_user, nama_user, level FROM user WHERE nama_user=? AND password=?";
            PreparedStatement stat = conn.prepareStatement(query);
            stat.setString(1, username);
            stat.setString(2, password);
            
            System.out.println("SQL Query: " + query);
            
            ResultSet rs = stat.executeQuery();
            
            if (rs.next()) {
                String userId = rs.getString("id_user");
                String namaUser = rs.getString("nama_user");
                String levelUser = rs.getString("level");
                
                System.out.println("Database result - UserId: " + userId + ", NamaUser: " + namaUser + ", LevelUser: " + levelUser);
                
                // Set ke UserSession
                UserSession.setUserId(userId);
                UserSession.setNamaUser(namaUser);
                UserSession.setLevelUser(levelUser);
                
                System.out.println("Verification - UserId: " + UserSession.getUserId() + ", NamaUser: " + UserSession.getNamaUser() + ", LevelUser: "+ UserSession.getLevelUser());
                
                JOptionPane.showMessageDialog(null, "Login Berhasil! Selamat datang, " + namaUser);
                
                // Buka Main Menu
                Main_Menu u = new Main_Menu();
                u.setVisible(true);
                this.dispose();
                
            } else {
                System.out.println("Login failed - No matching user found");
                JOptionPane.showMessageDialog(null, "Login Gagal! Username atau Password salah.");
                kosong();
            }
            
            rs.close();
            stat.close();
            
        } catch (SQLException ex) {
            System.out.println("SQL Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error Database: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        String username = txtusername.getText();
        if (username.equals("Username")) {
            txtusername.setText("");
            txtusername.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        String username = txtusername.getText();
        if (username.trim().equals("")) {
            txtusername.setText("Username");
            txtusername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtusernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel key;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
