package Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import java.util.Date;
import java.text.SimpleDateFormat;

public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
        setStaffInfo();
        execute();
        Date();
    }
    
    private void setStaffInfo() {
        System.out.println("setStaffInfo() called");
        
        if (UserSession.isLoggedIn()) {
            String idStaff = UserSession.getUserId();
            String namaStaff = UserSession.getNamaUser();
            String levelStaff = UserSession.getLevelUser();
            
            System.out.println("Setting labels - ID: " + idStaff + ", Nama: " + namaStaff + ", Level: " + levelStaff);
            
            jId.setText(idStaff);
            jNama.setText(namaStaff);
            jLevel.setText(levelStaff);
            
            System.out.println("Labels set - jId: " + jId.getText() + ", jNama: " + jNama.getText() + ", jLevel: " + jLevel.getText());
        } else {
            System.out.println("User not logged in, setting default values");
            jId.setText("UNKNOWN");
            jNama.setText("Guest User");
            jLevel.setText("Guest");
        }
    }
    
    public void refreshUserInfo() {
        System.out.println("refreshUserInfo() called");
        setStaffInfo();
    }
    
    private void Date() {
        Date TanggalSekarang = new Date ();
        SimpleDateFormat TanggalWaktu = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String tanggal = TanggalWaktu.format(TanggalSekarang);
        jTanggal.setText(tanggal);
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTanggal = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JPanel();
        Session = new javax.swing.JPanel();
        jLevel = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        menu_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1009, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        navbar.setBackground(new java.awt.Color(0, 51, 153));
        navbar.setPreferredSize(new java.awt.Dimension(650, 70));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Gudang Aquatic");

        jTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jTanggal.setText("jLabel2");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(290, 450));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menu);

        Session.setBackground(new java.awt.Color(255, 255, 255));
        Session.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        jLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLevel.setText("LEVEL");

        jNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNama.setText("NAMA");

        jId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jId.setText("ID");

        javax.swing.GroupLayout SessionLayout = new javax.swing.GroupLayout(Session);
        Session.setLayout(SessionLayout);
        SessionLayout.setHorizontalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SessionLayout.setVerticalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(Session, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        menu_utama.setBackground(new java.awt.Color(255, 255, 255));
        menu_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1023, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        menu_utama.add(new content());
        menu_utama.repaint();
        menu_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Session;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTanggal;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menu_utama;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/images/master_icon.png"));
        ImageIcon iconMasterBarang = new ImageIcon(getClass().getResource("/images/box.png"));
        ImageIcon iconMasterSupplier = new ImageIcon(getClass().getResource("/images/supplier.png"));
        ImageIcon iconMasterToko = new ImageIcon(getClass().getResource("/images/toko.png"));
        ImageIcon iconMasterMobil = new ImageIcon(getClass().getResource("/images/car.png"));
        ImageIcon iconTransaction = new ImageIcon(getClass().getResource("/images/transaction.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/images/report.png"));
        
        Menu_item masBarang = new Menu_item(null, true,iconMasterBarang, "Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    menu_utama.removeAll();
                    menu_utama.add(new Form_Barang());
                    menu_utama.repaint();
                    menu_utama.revalidate();
            }
        });
        Menu_item masSupplier = new Menu_item(null, true,iconMasterSupplier, "Supplier", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    menu_utama.removeAll();
                    menu_utama.add(new Form_Supplier());
                    menu_utama.repaint();
                    menu_utama.revalidate();
            }
            
        });
        Menu_item masToko = new Menu_item(null, true,iconMasterToko, "Toko", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Form_Toko());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item masMobil = new Menu_item(null, true,iconMasterMobil, "Mobil", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Form_Mobil());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item barangMasuk = new Menu_item(null, true,iconTransaction, "Barang Masuk", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Form_Barang_Masuk());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item barangKeluar = new Menu_item(null, true,iconTransaction, "Barang Keluar", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Form_Barang_Keluar());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item stok = new Menu_item(null, true,iconTransaction, "Stok Utama", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Form_Stok_Utama());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item report_masuk = new Menu_item(null, true,iconReport, "Report Barang Masuk", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Report_Barang_Masuk());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        Menu_item report_keluar = new Menu_item(null, true,iconReport, "Report Barang Keluar", new ActionListener() {
                        @Override
            public void actionPerformed(ActionEvent e) {
                   menu_utama.removeAll();
                   menu_utama.add(new Report_Barang_Keluar());
                   menu_utama.repaint();
                   menu_utama.revalidate();
            }
        });
        
        
        Menu_item menuMaster = new Menu_item(iconMaster, false, null, "Master", null, masBarang,masSupplier,masToko,masMobil);
        Menu_item menuTransaksi = new Menu_item(iconTransaction, false, null, "Transaksi", null,barangMasuk,barangKeluar,stok);
        Menu_item menuReport = new Menu_item(iconReport, false, null, "Report", null,report_masuk,report_keluar);
        
        addMenu(menuMaster,menuTransaksi,menuReport);

    }   
        private void addMenu(Menu_item... menu) {
        for (int i = 0; i <menu.length; i++) {
            this.menu.add(menu[i]);
            java.util.ArrayList<Menu_item> subMenu = menu[i].getSubMenu();
            for (Menu_item m : subMenu) {
            addMenu(m);
            }
        }
        revalidate();
        repaint();
    }



    
}
